--1
-- top seelling items
SELECT ITEM_SK, SUM(DAILY_QTY) AS total_quantity_sold
FROM TPCDS.INTERMEDIATE.DAILY_AGGREGATED_SALES
where SOLD_YR_NUM = 2023
GROUP BY ITEM_SK
ORDER BY total_quantity_sold DESC
LIMIT 10;

--2
--The sum of sales_quantity--
-- all years
SELECT SOLD_YR_NUM,SUM(SUM_QTY_WK) AS Total_Sales_Quantity
FROM TPCDS.ANALYTICS.WEEKLY_SALES_INVENTORY
group BY SOLD_YR_NUM;
--weeks of 2020
SELECT SOLD_WK_NUM,SUM(SUM_QTY_WK) AS Total_Sales_Quantity_2022
FROM TPCDS.ANALYTICS.WEEKLY_SALES_INVENTORY
WHERE SOLD_YR_NUM = 2020
group BY SOLD_WK_NUM;
-- weeks of 2021
SELECT SOLD_WK_NUM,SUM(SUM_QTY_WK) AS Total_Sales_Quantity_2022
FROM TPCDS.ANALYTICS.WEEKLY_SALES_INVENTORY
WHERE SOLD_YR_NUM = 2021
group BY SOLD_WK_NUM;
-- weeks of 2022
SELECT SOLD_WK_NUM,SUM(SUM_QTY_WK) AS Total_Sales_Quantity_2022
FROM TPCDS.ANALYTICS.WEEKLY_SALES_INVENTORY
WHERE SOLD_YR_NUM = 2022
group BY SOLD_WK_NUM;
-- weeks of 2023
SELECT SOLD_WK_NUM,SUM(SUM_QTY_WK) AS Total_Sales_Quantity_2022
FROM TPCDS.ANALYTICS.WEEKLY_SALES_INVENTORY
WHERE SOLD_YR_NUM = 2023
group BY SOLD_WK_NUM;
-- weeks of 2024
SELECT SOLD_WK_NUM,SUM(SUM_QTY_WK) AS Total_Sales_Quantity_2022
FROM TPCDS.ANALYTICS.WEEKLY_SALES_INVENTORY
WHERE SOLD_YR_NUM = 2024
group BY SOLD_WK_NUM;


--3
--Total Sales Amount by State
SELECT CA_STATE, SUM(DAILY_SALES_AMT) AS Total_Sales_Amount
FROM TPCDS.INTERMEDIATE.DAILY_AGGREGATED_SALES das
JOIN TPCDS.ANALYTICS.CUSTOMER_DIM cd ON das.WAREHOUSE_SK = cd.C_CURRENT_ADDR_SK
GROUP BY CA_STATE
ORDER BY Total_Sales_Amount DESC;
--Total Customers by State:
SELECT CA_STATE, COUNT(DISTINCT C_CUSTOMER_SK) AS Total_Customers
FROM TPCDS.ANALYTICS.CUSTOMER_DIM
GROUP BY CA_STATE
ORDER BY Total_Customers DESC;